{
    "name": "Custom Report",
    "images": ["static/description/icon.png"],
    "summary": "Custom report adding features to sale order",
    "author": "Ismael Semmar Galvez",
    "website": "https://github.com/Ism1tha/technical-training",
    "version": "16.0.0",
    "application": True,
    'depends': ['base', 'sale'],
    "data": [ 
        "security/ir.model.access.csv",
        "views/sale_order_report_extension.xml",
        "views/sale_order_view_extension.xml",
        'views/custom_report_view.xml',
        'views/custom_report_action.xml',
        'views/custom_report_menu.xml',
        'views/custom_report_report.xml',
        'reports/custom_report_template.xml',
    ],
    "installable": True,
    'license': 'LGPL-3',   
}
